title: Ngo Thi Bao Tram
description: Postdoctoral fellow
baseurl: "/tramngo18.github.io"
url: ""
repository: TramNgo18/TramNgo18.github.io
paginate: 28

banner: "/assets/IMG_4951.JPG" # site banner (load when someone share your page url)
favicon: "/assets/IMG_4951.JPG" # site's favicon (icon left side of your page)

# MatJek specific configurations
user: 
  name: "Tram Ngo"
  email: ""
  website: ""
  avatar: "/assets/IMG_4951.JPG"
  github: ""
google_tracking_id: ""
google_site_verification: ""
disqus_shortname: this-site

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title


gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed

  future: true
